name: shapmanpaypoint
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dropdown_search: ^5.0.6
  card_swiper: ^3.0.1
  get_storage:
  pin_code_fields: ^8.0.1
  flutter_dialpad: ^1.0.5
  local_auth: ^2.1.7
  permission_handler: ^11.3.1
  freezed_annotation: ^2.4.1
  intl: ^0.17.0
  dio: ^5.4.1
  flutter_secure_storage: ^9.2.2
  contacts_service:
  dart_jsonwebtoken: ^2.13.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
#  flutter_paystack: ^1.0.7
  string_validator: ^1.0.2
  envied: ^0.5.4+1
  mocktail: ^1.0.3
  loading_animation_widget: ^1.2.1
  carousel_slider: ^5.0.0
  html_unescape: ^2.0.0
  flutter_svg: ^2.0.9
  flutter_progress_hud: ^2.0.2
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.1.2
  web_socket_channel: ^3.0.1
  path_provider: ^2.1.3
  share_plus: ^10.0.0
  flutter_native_splash: ^2.4.0
dependency_overrides:
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4+1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/airtime/
    - lib/assets/electric/
    - lib/utils/jsons/countryIso.json
    - lib/utils/jsons/data_operators.json
    - lib/utils/jsons/utility.json
    - lib/utils/jsons/images.json
    - lib/utils/jsons/bank_list.json
    - lib/assets/env/.env.dev
    - lib/assets/env/.env.prod

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Inter/static/Inter-Black.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Shantell_Sans
      fonts:
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/ShantellSans-Italic-VariableFont_BNCE,INFM,SPAC,wght.ttf
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/ShantellSans-VariableFont_BNCE,INFM,SPAC,wght.ttf
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/Shantell_Sans/static/ShantellSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Poppin
      fonts:
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset:  assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter,Roboto,Shantell_Sans/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
